Update index.html
CodeForMyFriends/create-a-simple-web-the-cool-gang pull request #7
Opened 2021-03-23 23:09 UTC by johaan1515

te he+

2021-03-23 23:10 UTC, Star-Cyber3 commented
hi
hi

2021-03-23 23:14 UTC, Star-Cyber3 reviewed
d

2021-03-23 23:14 UTC, Star-Cyber3 commented on index.html
> +  <h1 poopoo boi is not cool /h1>
```suggestion
  <h1>poopoo boi is not cool </h1>
```

2021-03-23 23:17 UTC, Star-Cyber3 requested changes
Cant pass

2021-03-23 23:20 UTC, Star-Cyber3 requested changes
Click

2021-03-23 23:20 UTC, Star-Cyber3 commented on index.html
> +    <h2 he relly isint /h2>
```suggestion
    <h2> he relly isint </h2>
```

2021-03-23 23:21 UTC, johaan1515 commented
E

2021-03-23 23:25 UTC, Star-Cyber3 reviewed
NOPE

2021-03-23 23:25 UTC, Star-Cyber3 commented on index.html
> +        <head /h5>
```suggestion
  </head>
  <body>
  <h1> poopoo boi is not cool </h1>
    <h2> he relly isint </h2>
    <h3> he sucks </h3>
      <h4> NOOB </h4>
      </body>
   
```

2021-03-28 15:57 UTC, Star-Cyber3 commented on index.html
> +        <head>
```suggestion
    <h3> he sucks </h3>
      <h4> NOOB </h4>
        </body>
```
```suggestion
    <h3. he sucks /h3>
      <h4> NOOB /h4>
        <head>
```

2021-03-28 15:58 UTC, Star-Cyber3 commented on index.html
>  <head>
```suggestion
<head>
</head>
<body>
```

2021-03-28 15:59 UTC, Star-Cyber3 commented on index.html
>  <head>
```suggestion
<head>
</head>
<body>
```

2021-03-28 15:59 UTC, Star-Cyber3 commented on index.html
> +</head>
```suggestion

```

2021-03-28 16:00 UTC, Star-Cyber3 approved these changes
YES

2021-03-28 16:00 UTC, merged